### ISSUE TITLE
Add the `.env` file description

### ISSUE THREAD

**Issue by Mixail132** [RuslanSlepuhin/server_bot#366]
### Description:
The issue is to create an instruction on how to fill out the `.env` file.
### Tasks:
 - [ ] Add a new description `.env` file.
 - [ ] Link this file in `README.md`. 
 - [ ] Match the `example.env` variables.
### Issues:
#360
